default_initial_settings = {
    "name": "101Hero",
    "manufacturer": "101Hero",
    "start_gcode": "G21       ;metric values\nG90       ;absolute positioning\nM82       ;set extruder to absolute mode\nM107      ;start with the fan off\nG28 Z0    ;home Z\nG1 Z15.0 F840\nG92 E0    ;zero the extruded length\nG1 F200 E3              ;extrude 3mm of feed stock\nG92 E0                  ;zero the extruded length again\nG1 F840\n;Put printing message on LCD screen\nM117 Printing...\n",
    "end_gcode": "M104 S0     ;extruder heater off\nM140 S0     ;heated bed heater off (if you have it)\nG91         ;relative positioning\nG1 E-1 F300 ;retract the filament a bit\nG1 Z0.5 E-5 F840 ;move Z up a bit and retract even more\nG28 X0 Y0   ;home X/Y, so the head is out of the way\nM84         ;steppers off\nG90         ;absolute positioning",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 100,
    "print_speed": 14,
    "travel_speed": 14,
    "dia_feed": 2.85,
    "build_volume_x": 149.86,
    "build_volume_y": 149.86,
    "build_volume_z": 99.822,
}
