default_initial_settings = {
    "name": "Anycubic Kossel Pulley",
    "manufacturer": "Anycubic",
    "start_gcode": "G21        ;metric values\nG90        ;absolute positioning\nM107       ;start with the fan off\nG28   ;move to endstops\nG92 E0                  ;zero the extruded length\nG1 F200 E3              ;extrude 3mm of feed stock\nG92 E0                  ;zero the extruded length again\nG1 F{data['travel_speed']}\n;Put printing message on LCD screen\nM117 Printing...",
    "end_gcode": "M400      ;Free buffer\nG91      ;relative positioning\nG1 E-1 F300      ;retract the filament a bit before lifting the nozzle, to release some of the pressure\nG1 F{data['travel_speed']} Z+1 E-5        ;move Z up a bit and retract filament even more\nG90      ;absolute positioning\nM104 S0      ;extruder heater off\nM140 S0      ;heated bed heater off\nM107      ;fan off\nM84      ;steppers off\nG28      ;move to endstop\nM84      ;steppers off",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 100,
    "print_speed": 60,
    "travel_speed": 120,
    "dia_feed": 2.85,
    "build_volume_x": 180,
    "build_volume_y": 180,
    "build_volume_z": 300,
}
