default_initial_settings = {
    "name": "BQ Witbox 2",
    "manufacturer": "BQ",
    "start_gcode": "; -- START GCODE --\nM800        ; Custom GCODE to fire start print procedure\n; -- end of START GCODE --",
    "end_gcode": "; -- END GCODE --\nM801        ; Custom GCODE to fire end print procedure\n; -- end of END GCODE --",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 100,
    "print_speed": 60,
    "travel_speed": 120,
    "dia_feed": 2.85,
    "build_volume_x": 297,
    "build_volume_y": 210,
    "build_volume_z": 200,
}
