default_initial_settings = {
    "name": "Extruder",
    "manufacturer": "Unknown",
    "start_gcode": "",
    "end_gcode": "",
    "bed_temp": None,
    "nozzle_temp": None,
    "material_flow_percent": None,
    "print_speed": None,
    "travel_speed": None,
    "dia_feed": 2.85,
    "build_volume_x": None,
    "build_volume_y": None,
    "build_volume_z": None,
}
