default_initial_settings = {
    "name": "Felix Tec 4 Dual",
    "manufacturer": "Felix",
    "start_gcode": "; FELIXprinters | www.FELIXprinters.com | Zeemanlaan 15 3401 MV IJsselstein The Netherlands\n; FELIX Tec 4 | Start Code Dual Extruders v1.0\n; Modified by kerog777@gmail.com\n;================================ \n;Initializing\nM80   ; Turn on the power supply\nM107     ; Turn off fans\nM117 Heating up\nM190 S{data['bed_temp']}   ; Heatup Bed\nM104 T0 S120\nM104 T1 S120\nG28             ; Home all\nM109 T0 S{data['nozzle_temp']}   ; Heatup hot-end\nM117 Purging\nT0    ; Select extruder 1\nG92 E0    ; Reset extruder\nG1 X10.0 Y1.1 Z5.0 F15240   ; Move to start-line position\nG1 Z0.3 F15240    ; Move z up\nG1 X127.0 Y1.1 Z0.3 F1500.0 E15    ; Purge 1st line\nG92 E0    ; Reset extruder\n\n;================================ ; Initializing done\nM117 FELIXprinting",
    "end_gcode": "; FELIXprinters End Code Tec Series v1.0\n; Modified by kerog777@gmail.com\n; ================================= \n; Move extruder to park position\nG91       ; Make coordinates relative\nG1 Z2 F1000       ; Move z 2mm up\nG90       ; Use absolute coordinates again\nG1 X0 Y0 F15240   ; Move bed and printhead to ergonomic position\n\n; ================================= ; Turn off heaters\nM140 S0    ; Turn off bed heater\nT0    ; Select left extruder\nM104 T0 S0    ; Turn off heater and continue\nG92 E0    ; Reset extruder position\nG1 E-6    ; Retract filament 8mm\nG92 E0    ; Reset extruder position\nT1    ; Select right extruder\nM104 T1 S0    ; Turn off heater and continue\nG92 E0    ; Reset extruder position\nG1 E-6    ; Retract filament 8mm\nG92 E0    ; Reset extruder position\nT0    ; Select left extruder\n\n; ================================= ; Turn the rest off\nM107        ; Turn off fan\nM84    ; Disable steppers\nM117 Finished Printing!",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 95,
    "print_speed": 60,
    "travel_speed": 120,
    "dia_feed": 2.85,
    "build_volume_x": 255,
    "build_volume_y": 205,
    "build_volume_z": 225,
}
