default_initial_settings = {
    "name": "gMax 1.5 Plus Dual Extruder",
    "manufacturer": "gCreate",
    "start_gcode": "G21 ;metric values\nG90 ;absolute positioning\nM82 ;set extruder to absolute mode\nM107 ;start with the fan off\nG28 ;Home X/Y/Z\nM104 S{data['nozzle_temp']} T0 ; Preheat Left Extruder\nM104 S{data['nozzle_temp']} T1 ; Preheat Right Extruder\nM109 S{data['nozzle_temp']} T0 ; Preheat Left Extruder\nM109 S{data['nozzle_temp']} T1 ; Preheat Right Extruder\nG91 ;relative positioning\nG90 ;absolute positioning\nM218 T1 X34.3 Y0; Set 2nd extruder offset. This can be changed later if needed\nG1 Z25.0 F9000 ;raise nozzle 25mm\nG92 E0 ;zero the extruded length again\nG1 F9000\n;Put printing message on LCD screen\nM117 Printing...",
    "end_gcode": "M104 S0 T0;Left extruder off\nM104 S0 T1; Right extruder off\nM140 S0 ;heated bed heater off (if you have it)\nG91 ;relative positioning\nG1 E-1 F300  ;retract the filament a bit before lifting the nozzle, to release some of the pressure\nG1 Z+0.5 E-5 X-20 Y-20 F9000 ;move Z up a bit and retract filament even more\nG28 X0 Y0 ;move X/Y to min endstops, so the head is out of the way\nM84 ;steppers off\nG90 ;absolute positioning",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 100,
    "print_speed": 50,
    "travel_speed": 120,
    "dia_feed": 1.75,
    "build_volume_x": 406,
    "build_volume_y": 406,
    "build_volume_z": 533,
}
