default_initial_settings = {
    "name": "TinyBoy Fabrikator Mini 1.5",
    "manufacturer": "TinyBoy",
    "start_gcode": "G21        ;metric values\nG90        ;absolute positioning\nM82        ;set extruder to absolute mode\nM107       ;start with the fan off\nG28 X0 Y0  ;move X/Y to min endstops\nG28 Z0     ;move Z to min endstops\nG1 X0.0 Y0.0 Z15.0 F6000 ;move the printhead up 15mm\nG92 E0                  ;zero the extruded length\nM104 S{data['nozzle_temp']} ;set extruder temperature\nM105\nM109 S{data['nozzle_temp']} ;wait for extruder temperature\nG1 F200 E30              ;extrude 30mm of feed stock\nG92 E0                  ;zero the extruded length again\nG1 F6000\n;Put printing message on LCD screen\nM117 Printing...",
    "end_gcode": ";End GCode\nM104 S0 ;extruder heater off\nM140 S0 ;heated bed heater off (if you have it)\nG91 ;relative positioning\nG1 E-1 F300 ;retract the filament a bit before lifting the nozzle, to release some of the pressure\nG1 Z+0.5 E-5 X-20 Y-20 F6000 ;move Z up a bit and retract filament even more\nG28 X0 Y0 ;move X/Y to min endstops, so the head is out of the way\nM84 ;steppers off\nG90 ;absolute positioning",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 100,
    "print_speed": 60,
    "travel_speed": 120,
    "dia_feed": 2.85,
    "build_volume_x": 80,
    "build_volume_y": 80,
    "build_volume_z": 80,
}
