default_initial_settings = {
    "name": "UltiMaker Method Base Profile",
    "manufacturer": "Ultimaker B.V.",
    "start_gcode": "",
    "end_gcode": "",
    "bed_temp": 60,
    "nozzle_temp": 210,
    "material_flow_percent": 97,
    "print_speed": 50,
    "travel_speed": 250,
    "dia_feed": 2.85,
    "build_volume_x": 100,
    "build_volume_y": 100,
    "build_volume_z": 100,
}
